export default class ACTIONTYPES {
    static DISCOVER_FILTER_CHANGED = 'DISCOVER_FILTER_CHANGED';
    static TAB_CHANGED = 'TAB_CHANGED';
    static USER_LOGGED_IN = 'USER_LOGGED_IN';
    static USER_LOGGED_OUT = 'USER_LOGGED_OUT';
    static COURSE_CHANGED = 'COURSE_CHANGED';
    static COURSE_SAVED = 'COURSE_SAVED';
    static FRIENDS_POPULATED = 'FRIENDS_POPULATED';
}